env:
  JULIA_VERSION: "1.7.3"
  OPENMPI_VERSION: "4.0.4"
  CUDA_VERSION: "11.2"
  OPENBLAS_NUM_THREADS: 1
  CLIMATEMACHINE_SETTINGS_FIX_RNG_SEED: "true"
  BUILDKITE_COMMIT: "${BUILDKITE_COMMIT}"
  BUILDKITE_BRANCH: "${BUILDKITE_BRANCH}"
  JULIA_DEPOT_PATH: "${BUILDKITE_BUILD_PATH}/${BUILDKITE_PIPELINE_SLUG}/depot/cpu"

agents:
  config: cpu
  queue: central
  slurm_ntasks: 1

steps:
  - label: "init environment :computer:"
    key: "init_cpu_env"
    command:
      - "echo $$JULIA_DEPOT_PATH"

      - echo "--- Instantiate integration_tests"
      - "julia --project=integration_tests -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=integration_tests -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=integration_tests -e 'using Pkg; Pkg.status()'"

      - echo "--- Instantiate perf"
      - "julia --project=perf -e 'using Pkg; Pkg.instantiate(;verbose=true)'"
      - "julia --project=perf -e 'using Pkg; Pkg.precompile()'"
      - "julia --project=perf -e 'using Pkg; Pkg.status()'"

      - echo "--- Download artifacts"
      - "julia --project=integration_tests integration_tests/download_artifacts.jl"

  - wait

  - group: "Vanilla Experiments"
    steps:

      - label: ":partly_sunny: Bomex"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex"
        artifact_paths: "Output.Bomex.01/stats/comparison/*"

      - label: ":partly_sunny: life_cycle_Tan2018"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case life_cycle_Tan2018"
        artifact_paths: "Output.life_cycle_Tan2018.01/stats/comparison/*"

      - label: ":partly_sunny: Soares"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Soares"
        artifact_paths: "Output.Soares.01/stats/comparison/*"

      - label: ":partly_sunny: Rico"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Rico"
        artifact_paths: "Output.Rico.01/stats/comparison/*"

      - label: ":partly_sunny: Nieuwstadt"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Nieuwstadt"
        artifact_paths: "Output.Nieuwstadt.01/stats/comparison/*"

      - label: ":scissors: TRMM_LBA"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case TRMM_LBA"
        artifact_paths: "Output.TRMM_LBA.01/stats/comparison/*"

      - label: ":partly_sunny: ARM_SGP"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case ARM_SGP"
        artifact_paths: "Output.ARM_SGP.01/stats/comparison/*"

      # Run for short time since it's long...
      #- label: ":partly_sunny: GATE_III"
      #  command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case GATE_III --t_max 86400.0"
      #  artifact_paths: "Output.GATE_III.01/stats/comparison/*"

      - label: ":partly_sunny: DYCOMS_RF01"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case DYCOMS_RF01"
        artifact_paths: "Output.DYCOMS_RF01.01/stats/comparison/*"

      - label: ":partly_sunny: DYCOMS_RF02"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case DYCOMS_RF02"
        artifact_paths: "Output.DYCOMS_RF02.01/stats/comparison/*"

      - label: ":partly_sunny: GABLS"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case GABLS"
        artifact_paths: "Output.GABLS.01/stats/comparison/*"

      - label: ":thought_balloon: DryBubble"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case DryBubble"
        artifact_paths: "Output.DryBubble.01/stats/comparison/*"

      - label: ":partly_sunny: LES_driven_SCM"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case LES_driven_SCM"
        artifact_paths: "Output.LES_driven_SCM.01/stats/comparison/*"

  - group: "Vanilla + Deviations"
    steps:

      - label: ":partly_sunny: Bomex with gaussian"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --sgs quadrature --quad_type gaussian --skip_tests true --suffix _gaussian"
        artifact_paths: "Output.Bomex.01_gaussian/stats/comparison/*"

      - label: ":partly_sunny: LES_driven_SCM with stretched grid"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case LES_driven_SCM --stretch_grid true --skip_tests true --suffix _stretch_grid_true"
        artifact_paths: "Output.LES_driven_SCM.01_stretch_grid_true/stats/comparison/*"

      - label: ":partly_sunny: Bomex with NN_nonlocal"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --entr NN_nonlocal --entr_dim_scale inv_z --detr_dim_scale inv_z --area_limiter_power 0.0 --dt_max 2.0 --nn_ent_biases true --skip_tests true --suffix _NN_nonlocal"
        artifact_paths: "Output.Bomex.01_NN_nonlocal/stats/comparison/*"

      - label: ":partly_sunny: Bomex with NN"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --entr NN --entr_dim_scale inv_z --detr_dim_scale inv_z --area_limiter_power 0.0 --dt_max 2.0 --nn_ent_biases true --skip_tests true --suffix _NN"
        artifact_paths: "Output.Bomex.01_NN/stats/comparison/*"

      - label: ":partly_sunny: Bomex with FNO"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --entr FNO --skip_tests true --broken_tests true --suffix _FNO"
        artifact_paths: "Output.Bomex.01_FNO/stats/comparison/*"

      - label: ":partly_sunny: Bomex with RF"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --entr RF --skip_tests true --broken_tests true --suffix _RF"
        artifact_paths: "Output.Bomex.01_RF/stats/comparison/*"

      - label: ":partly_sunny: Bomex with noisy_relaxation_process"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --stoch_entr noisy_relaxation_process --skip_tests true --suffix _noisy_relaxation_process"
        artifact_paths: "Output.Bomex.01_noisy_relaxation_process/stats/comparison/*"

      - label: ":partly_sunny: Bomex with prognostic_noisy_relaxation_process"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --stoch_entr prognostic_noisy_relaxation_process --skip_tests true --suffix _prognostic_noisy_relaxation_process"
        artifact_paths: "Output.Bomex.01_prognostic_noisy_relaxation_process/stats/comparison/*"

      - label: ":partly_sunny: Bomex with multiple updrafts"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --n_up 2 --dt_max 8.0 --suffix _n_up_2 --skip_tests true"
        artifact_paths: "Output.Bomex.01_n_up_2/stats/comparison/*"

      - label: ":scissors: TRMM_LBA with non-equilibrium moisture"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case TRMM_LBA --sgs mean --adapt_dt false --dt 1.0 --moisture_model nonequilibrium --skip_tests true --suffix _nonequilibrium_moisture"
        artifact_paths: "Output.TRMM_LBA.01_nonequilibrium_moisture/stats/comparison/*"

      - label: ":scissors: TRMM_LBA with 0-moment precipitation"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case TRMM_LBA --sgs mean --adapt_dt false --dt 1.0 --precipitation_model cutoff --skip_tests true --suffix _0moment_precipitation"
        artifact_paths: "Output.TRMM_LBA.01_0moment_precipitation/stats/comparison/*"

      - label: ":scissors: TRMM_LBA with prescribed precipitation fraction"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case TRMM_LBA --sgs mean --adapt_dt false --dt 1.0 --precipitation_model clima_1m --precip_fraction_model prescribed --prescribed_precip_frac_value 0.42 --skip_tests true --suffix _prescribed_precipitation_fraction"
        artifact_paths: "Output.TRMM_LBA.01_prescribed_precipitation_fraction/stats/comparison/*"

      - label: ":scissors: TRMM_LBA with diagnostic precipitation fraction"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case TRMM_LBA --sgs mean --adapt_dt false --dt 1.0 --precipitation_model clima_1m --precip_fraction_model cloud_cover --precip_fraction_limiter 0.42 --skip_tests true --suffix _diagnostic_precipitation_fraction"
        artifact_paths: "Output.TRMM_LBA.01_diagnostic_precipitation_fraction/stats/comparison/*"

      - label: ":partly_sunny: Bomex with calibrate_io_true"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --calibrate_io true --skip_post_proc true --suffix _calibrate_io_true"
        artifact_paths: "Output.Bomex.01_calibrate_io_true/stats/comparison/*"

      - label: ":partly_sunny: Bomex with skip_io_true"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --skip_io true --skip_post_proc true --suffix _skip_io_true"
        artifact_paths: "Output.Bomex.01_skip_io_true/stats/comparison/*"

      - label: ":partly_sunny: Rico with prognostic covarinaces"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Rico --thermo_covariance_model prognostic --skip_tests true --suffix _prognostic_covarinaces"
        artifact_paths: "Output.Rico.01_prognostic_covarinaces/stats/comparison/*"

  - group: "Sphere cases"
    steps:

      - label: ":partly_sunny: Bomex on sphere"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --config sphere --set_src_seed true --skip_tests true --suffix _sphere"
        artifact_paths: "Output.Bomex.01_sphere/stats/comparison/*"

  - group: "Config testing"
    steps:

      - label: ":partly_sunny: Bomex duals"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --test_duals true --suffix _duals"
        artifact_paths: "Output.Bomex.01_duals/stats/comparison/*"

      - label: ":partly_sunny: Bomex with Float32"
        command: "julia --color=yes --project=integration_tests integration_tests/driver.jl --case Bomex --float_type Float32 --skip_tests true --suffix _float32"
        artifact_paths: "Output.Bomex.01_float32/stats/comparison/*"

  - group: "Performance monitoring"
    steps:

      - label: ":rocket: Allocations analysis"
        command: "julia --color=yes --project=perf perf/allocs.jl"

      - label: ":rocket: Allocations analysis (exhaustive)"
        command: "julia --color=yes --project=perf perf/allocs.jl exhaustive=true"

      - label: ":rocket: Benchmark tendencies"
        command: "julia --color=yes --project=perf perf/benchmark.jl"

      - label: ":rocket: Benchmark step!"
        command: "julia --color=yes --project=perf perf/benchmark_step.jl"

      - label: ":scales: Measure precompilation speedup (all)"
        command: "julia --color=yes --project=perf perf/precompilable.jl"

      - label: ":scales: Measure precompilation speedup (no init)"
        command: "julia --color=yes --project=perf perf/precompilable_no_init.jl"

      - label: ":scales: Measure precompilation speedup (no io)"
        command: "julia --color=yes --project=perf perf/precompilable_no_io.jl"

      - label: ":scales: Measure precompilation speedup (no init, no io)"
        command: "julia --color=yes --project=perf perf/precompilable_no_init_io.jl"

      - label: ":mag: Invalidations"
        command: "julia --color=yes --project=perf perf/invalidations.jl"
        artifact_paths: "perf/invalidations_output/*"

      - label: ":mag: Inference triggers"
        command: "julia --color=yes --project=perf perf/inference_triggers.jl"

      - label: ":mag: Jet test"
        command: "julia --color=yes --project=perf perf/jet.jl"

  - wait: ~
    continue_on_failure: true

  - label: ":robot_face: Print new mse tables"
    command: "julia --color=yes --project=integration_tests utils/print_new_mse.jl"

  - wait

  - label: ":robot_face: Move main results"
    command: "julia --color=yes --project=integration_tests utils/move_output.jl"
