# """ Bomex """

[dummy_param_name_1]
alias = "Pg"
value = 1.015e5 
type = "float"
description = "pressure at the ground"

[dummy_param_name_2]
alias = "qtg"
value = 0.02245
type = "float"
description = "total water mixing ratio at the surface"

[dummy_param_name_3]
alias = "Tg"
value = 300.4
type = "float"
description = "temperature at the ground"

[dummy_param_name_4]
alias = "zrough"
value =  1.0e-4
type = "float"

[dummy_param_name_5]
alias = "θ_surface"
value = 299.1
type = "float"

[dummy_param_name_6]
alias = "qsurface"
value =  22.45e-3
type = "float"

[dummy_param_name_7]
alias = "θ_flux"
value = 8.0e-3
type = "float"

[dummy_param_name_8]
alias = "qt_flux"
value = 5.2e-5
type = "float"

[dummy_param_name_9]
alias = "ustar"
value =  0.28
type = "float"
description = "to initialize grid mean covariances [m/s]"

[dummy_param_name_10]
alias = "coriolis_param"
value = 0.376e-4
type = "[s^{-1}]"

