# """ Dry Bubble """

[dummy_param_name_1]
alias = "Pg"
value = 1.0e5
type = "float"
description = "pressure at the ground"

[dummy_param_name_2]
alias = "qtg"
value = 1.0e-5
type = "float"

[dummy_param_name_3]
alias = "Tg"
value = 296.0
type = "float"


[dummy_param_name_4]
alias = "Tsurface"
value =  300.0
type = "float"

[dummy_param_name_5]
alias = "qsurface"
value = 0.0
type = "float"

[dummy_param_name_6]
alias = "shf"
value = 0.0001
type = "float"

[dummy_param_name_7]
alias = "lhf"
value = 0.0001
type = "float"

[dummy_param_name_8]
alias = "ustar"
value = 0.1
type = "float"


