# """ GATE_III Khairoutdinov 2009"""

[dummy_param_name_1]
alias = "Pg"
value =  101300.0  
type = "float"
description = "pressure at the ground"

[dummy_param_name_2]
alias = "qtg"
value = 0.0165 
type = "float"

[dummy_param_name_3]
alias = "Tg"
value = 299.184
type = "float"
description = "temperature at the ground"

[dummy_param_name_4]
alias = "zrough"
value =  0.00015
type = "float"

[dummy_param_name_5]
alias = "qsurface"
value = 0.0165
type = "float"

[dummy_param_name_6]
alias = "cm"
value =  0.0012
type = "float"

[dummy_param_name_7]
alias = "ch"
value =0.0034337
type = "float"

[dummy_param_name_8]
alias = "cq"
value = 0.0034337
type = "float"

[dummy_param_name_9]
alias = "Tsurface"
value = 299.184
type = "float"
