# """ LES_driven_SCM """

[dummy_param_name_1]
alias = "zrough"
value = 1.0e-4
type = "float"

[dummy_param_name_2]
alias = "ustar"
value = 0.0
type = "float"

[dummy_param_name_3]
alias = "coriolis_param"
value = 0.376e-4
type = "float"


